# Generated by Django 4.2.4 on 2023-09-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.client')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.courier')),
                ('pizza', models.ManyToManyField(to='pizzeria.pizzatype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.state')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
