# Generated by Django 4.2.4 on 2023-09-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='cart', max_length=255, unique=True),
        ),
    ]
