# Generated by Django 4.2.4 on 2023-09-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.courier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.state'),
        ),
    ]
