# Generated by Django 4.2.4 on 2023-09-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pizza',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.pizzatype')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='pizzeria.cartitem'),
        ),
    ]
