# Generated by Django 4.2.4 on 2023-09-24 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0008_remove_cart_pizza_cartitem_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.pizzatype'),
        ),
    ]
