# Generated by Django 4.2.4 on 2023-09-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0010_remove_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='pizzeria.cartitem'),
        ),
    ]
